version: '3.2'

services:
  auth-service:
    build: ./auth-service
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./auth-service:/app

  contas-service-db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: contas_service_db
      POSTGRES_PASSWORD: contas_service_db
      POSTGRES_DB: contas_service_db
    volumes:
      - ./contas-service-db:/var/lib/postgresql/data
