version: '3.2'

services:
  auth-service:
    build: ./back/auth-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - auth-service-db
    environment:
      - MONGODB_HOST=auth-service-db
    volumes:
      - ./back/auth-service:/app
    networks:
      - bantads_network

  auth-service-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./auth-service-db:/data/db
    networks:
      - bantads_network

  contas-service-db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: contas_service_db
      POSTGRES_PASSWORD: contas_service_db
      POSTGRES_DB: contas_service_db
    volumes:
      - ./contas-service-db:/var/lib/postgresql/data
    networks:
      - bantads_network

  gerente-service-db:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: gerente_service_db
      POSTGRES_PASSWORD: gerente_service_db
      POSTGRES_DB: gerente_service_db
    volumes:
      - ./gerente-service-db:/var/lib/postgresql/data
    networks:
      - bantads_network

  rabbitmq:
    image: rabbitmq:3.13-rc-management 
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - bantads_network

  crudgerente:
    build: ./back/crud-gerente
    restart: always
    ports:
      - 5000:3100
    networks:
      - bantads_network
    volumes:
      - ./back/crud-gerente:/app
    depends_on:
      - gerente-service-db

networks:
  bantads_network:
    driver: bridge